version: '2'
services:
    songtranscriptmarket-app:
        image: songtranscriptmarket
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://songtranscriptmarket-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=songtranscriptmarket
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    songtranscriptmarket-mongodb:
        extends:
            file: mongodb.yml
            service: songtranscriptmarket-mongodb
